### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by arpitjaswani** [jenniferkaplannyc/jenniferkaplannyc.github.io#1]
typo in resume pdf, backend skills = Heruku > Heroku

**Comment by jenniferkaplannyc** [comment]
Thank you! I am fixing that now! As an FYI, I am doing a major revision of my portfolio right now. Please excuse any CSS ugliness happening right now.

**Comment by jenniferkaplannyc** [comment]
Okay in case you are looking at my site, the ugliness bug has been resolved. Thank you for being so helpful! Did you sign up for Hacktoberfest? If you do 5 PRs this month, you get a free tshirt. You can sign up at https://hacktoberfest.digitalocean.com/.

**Comment by arpitjaswani** [comment]
i was just checking out  the portfolio, was not on bug finding :D 
That's a good competition, thanks for letting me know. I am starting to contribute to open source.
